import type { Metadata } from "next";
import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const mainFont = Playfair_Display({
  variable: "--font-playfair-serif",
  subsets: ["latin"],
});

const bodyFont = Lato({
  variable: "--font-lato-sans",
  weight : ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.variable} ${bodyFont.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}